title: "CTI RSS 配置"
rss:
  CustomRSS:
    enabled: false
    filename: "CustomRSS.opml"
  CyberSecurityRSS:
    enabled: false
    url: "https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/CyberSecurityRSS.opml"
    filename: "CyberSecurityRSS.opml"
  CyberSecurityRSS-tiny:
    enabled: false
    url: "https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/tiny.opml"
    filename: "CyberSecurityRSS-tiny.opml"
  Chinese-Security-RSS:
    enabled: true
    url: "https://raw.githubusercontent.com/zhengjim/Chinese-Security-RSS/master/Chinese-Security-RSS.opml"
    filename: "Chinese-Security-RSS.opml"
  awesome-security-feed:
    enabled: false
    url: "https://raw.githubusercontent.com/mrtouch93/awesome-security-feed/main/security_feeds.opml"
    filename: "awesome-security-feed.opml"
  wechatRSS:
    enabled: true
    url: "https://wechat2rss.xlab.app/opml/sec.opml"
    filename: "wechatRSS.opml"
  chinese-independent-blogs:
    enabled: false
    url: "https://raw.githubusercontent.com/timqian/chinese-independent-blogs/master/feed.opml"
    filename: "chinese-independent-blogs.opml"
